Add food expense policy to travel fellowship
OBF/obf-docs pull request #122
Opened 2024-11-19 16:29 UTC by gedankenstuecke

As discussed during the board hangout on Nov 19, 2024, adding in the clarification for food expenses being eligible up to a daily cap.

2024-11-19 16:31 UTC, nlharris requested changes

2024-11-19 16:31 UTC, nlharris commented on Travel_fellowships.md
> +Expenses for food during are eligible up to a daily limit of $40 (receipts are required for reimbursement).
```suggestion
Expenses for food during the event are eligible up to a daily limit of $40 (receipts are required for reimbursement).
```

2024-11-19 16:31 UTC, nlharris commented on Travel_fellowships.md
> +Expenses for food during are eligible up to a daily limit of $40 (receipts are required for reimbursement).
fix typo
otherwise looks good

2024-11-19 16:33 UTC, gedankenstuecke commented on Travel_fellowships.md
> +Expenses for food during are eligible up to a daily limit of $40 (receipts are required for reimbursement).
Thanks @nlharris!

2024-11-19 16:40 UTC, nlharris approved these changes

2024-11-19 18:46 UTC, idoerg reviewed
I would fix to $40 (USD) to avoid confusing the Canadians, Australians, etc.

2024-11-19 19:02 UTC, peterjc commented
USD 40 would match the other usage (bar one $1000 which we should fix too).

[Personally I would write USD $40 and USD $1000 as the style?]

Also, how about we move "Receipts are required for reimbursement" to the end of the paragraph - we want to be clear this applies to everything.

2024-11-19 19:23 UTC, gedankenstuecke commented
Thanks, @idoerg & @peterjc. I've unified the currency as suggested - and also moved the bit on the receipt requirements down into the _Expenses_ section to cover both virtual and in-person events.

2024-11-19 19:42 UTC, hlapp requested changes

2024-11-19 19:42 UTC, hlapp commented on Travel_fellowships.md
> +The OBF Event Fellowships are available for the awardees to cover conference registration fees and other participation-related costs of up to USD $1,000.
```suggestion
The OBF Event Fellowships are available for the awardees to cover conference registration fees and other participation-related costs of up to USD 1,000. 
```
The dollar sign is ambiguous (there are a number of countries that use "dollar" as the name of their currency), and redundant with the actually very specific USD (US Dollar). (I.e., USD $1 literally reads _1 US dollar dollar_)

2024-11-19 19:42 UTC, hlapp commented on Travel_fellowships.md
> +The OBF Event Fellowships are available for the awardees to cover conference registration fees and other participation-related costs of up to USD $1,000.
```suggestion
The OBF Event Fellowships are available for the awardees to cover conference registration fees and other participation-related costs of up to USD 1,000. 
```
See above.

2024-11-19 19:42 UTC, hlapp commented on Travel_fellowships.md
> +The fellowship can be used to cover conference registration fees and direct travel costs (such as travel insurance, airfare, train, metro, bus and taxi), hotel, poster printing (if presenting a poste
```suggestion
The fellowship can be used to cover conference registration fees and direct travel costs (such as travel insurance, airfare, train, metro, bus and taxi), hotel, poster printing (if presenting a poster at the conference), and/or child-care up to a value of USD 1,000. 
```
See above.

2024-11-19 19:42 UTC, hlapp commented on Travel_fellowships.md
> +Expenses for food during the event are eligible up to a daily limit of USD $40.
```suggestion
Expenses for food during the event are eligible up to a daily limit of USD 40.
```

2024-11-19 19:42 UTC, hlapp commented on Travel_fellowships.md
> +If the applicants anticipate that they would require more than USD $1,000 to attend the event, they should include that information in the application form.
```suggestion
If the applicants anticipate that they would require more than USD 1,000 to attend the event, they should include that information in the application form.
```

2024-11-19 19:42 UTC, hlapp commented on Travel_fellowships.md
> +Please note that requests made for more than USD $1,000 may not be granted if not justified by the applicants.
```suggestion
Please note that requests made for more than USD 1,000 may not be granted if not justified by the applicants.
```

2024-11-19 19:42 UTC, hlapp commented on Travel_fellowships.md
> +The cost will be capped to a maximum of USD $40 each for small hardware such as headphones, webcam, speaker, and/or microphone.
```suggestion
The cost will be capped to a maximum of USD 40 each for small hardware such as headphones, webcam, speaker, and/or microphone.
```

2024-11-19 19:42 UTC, hlapp commented on Travel_fellowships.md
> +Please note that requests made for more than USD $1,000 may not be granted if not justified by the applicants.
```suggestion
Please note that requests made for more than USD 1,000 may not be granted if not justified by the applicants.
```

2024-11-19 19:48 UTC, hlapp commented
We also want to consider removing the thousands separator. Yes, it makes it easier to read, but comma is not the global standard. (According to the [Wikipedia entry](https://en.wikipedia.org/wiki/Decimal_separator) ` ` (space) is actually the international recommendation, though I'm not sure I've seen that often.)

2024-11-19 19:51 UTC, idoerg commented
My $0.02 (USD)

1. Keep the 1,000 separator so it is easier to read. I don't think anyone will think that we are capping at $1.

2. Add a definition of USD somewhere in the beginning (e.g. "US dollars or USD")

2024-11-21 11:41 UTC, hzahroh approved these changes

2024-11-21 11:48 UTC, merged

2024-11-21 11:49 UTC, peterjc commented
Thank you all.